### import libs for the program

In [3]:
import pandas as pd

In [4]:
print(pd.__version__)

0.20.3

#### download it from http://roycekimmons.com/system/generate_data.php?dataset=exams&n=100

In [15]:
exam_data = pd.read_csv('./data/exams.csv',quotechar='"')
exam_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group D,associate's degree,free/reduced,none,58,59,64
1,female,group B,high school,free/reduced,completed,46,59,69
2,male,group C,associate's degree,free/reduced,completed,66,68,64
3,female,group A,master's degree,free/reduced,none,57,76,72
4,male,group B,some high school,standard,completed,88,87,87
5,female,group C,bachelor's degree,standard,completed,52,69,68
6,male,group C,some high school,free/reduced,none,50,57,52
7,female,group C,bachelor's degree,standard,completed,82,93,95
8,male,group B,some college,standard,none,53,46,50
9,male,group B,some college,standard,none,55,55,51
10,male,group C,bachelor's degree,standard,none,69,65,61
11,female,group B,some college,standard,none,63,75,80
12,female,group C,some college,standard,none,41,46,48
13,female,group C,some college,standard,none,57,65,66
14,male,group C,high school,standard,completed,86,79,83
15,male,group D,some high school,standard,none,65,55,50
16,female,group E,master's degree,standard,none,96,91,91
17,female,group D,some college,standard,completed,79,94,99
18,male,group D,high school,free/reduced,completed,60,72,72
19,female,group C,bachelor's degree,standard,none,49,55,56
20,male,group B,associate's degree,standard,completed,67,63,65
21,female,group B,some high school,standard,completed,66,74,76
22,female,group A,high school,free/reduced,completed,51,73,70
23,male,group C,high school,free/reduced,none,79,64,63
24,male,group C,high school,standard,none,68,48,50
25,female,group B,some high school,standard,completed,86,88,94
26,male,group C,some high school,free/reduced,completed,68,71,59
27,female,group C,some college,standard,none,85,88,88
28,male,group E,some college,standard,completed,91,77,76
29,female,group D,bachelor's degree,free/reduced,none,66,82,81
...,...,...,...,...,...,...,...,...
70,female,group E,high school,free/reduced,none,49,61,63
71,male,group D,some college,standard,completed,64,64,62
72,female,group A,some college,standard,completed,63,65,71
73,female,group D,associate's degree,standard,none,73,89,89
74,male,group B,high school,standard,none,72,72,74
75,female,group D,master's degree,free/reduced,completed,74,76,82
76,female,group C,some college,standard,none,74,90,90
77,male,group C,high school,standard,none,64,60,59
78,male,group B,high school,standard,none,52,54,54
79,male,group C,some high school,free/reduced,none,46,47,42
80,female,group C,bachelor's degree,standard,completed,80,93,97
81,female,group B,associate's degree,standard,none,81,95,97
82,male,group C,associate's degree,free/reduced,completed,61,66,55
83,female,group C,bachelor's degree,free/reduced,none,56,78,74
84,male,group C,high school,free/reduced,none,27,28,22
85,male,group C,associate's degree,free/reduced,completed,60,65,57
86,male,group B,some high school,free/reduced,none,68,59,61
87,male,group B,some college,standard,none,56,63,59
88,male,group C,associate's degree,standard,completed,93,92,89
89,male,group A,master's degree,standard,completed,84,86,84
90,male,group B,some college,free/reduced,none,62,65,61
91,female,group C,some high school,standard,none,47,62,53
92,female,group B,bachelor's degree,standard,none,58,59,61
93,female,group C,bachelor's degree,standard,completed,81,95,88
94,female,group C,some high school,standard,completed,69,77,76
95,female,group B,associate's degree,free/reduced,completed,73,82,81
96,male,group A,bachelor's degree,standard,none,67,63,61
97,female,group C,bachelor's degree,free/reduced,none,48,52,52
98,female,group D,associate's degree,standard,none,81,87,88
99,male,group A,bachelor's degree,standard,none,87,76,75

In [16]:
math_avg = exam_data['math score'].mean()
reading_avg = exam_data['reading score'].mean()
writing_avg = exam_data['writing score'].mean()
print('Math Average',math_avg)
print('Reading Average',reading_avg)
print('Writing Average',writing_avg)

Math Average 65.17
Reading Average 68.44
Writing Average 68.16

In [17]:
from sklearn import preprocessing

#### scale will divide the score with average and substact standerd deviation

In [19]:
exam_data[['math score']] = preprocessing.scale(exam_data[['math score']])
exam_data[['reading score']] = preprocessing.scale(exam_data[['reading score']])
exam_data[['writing score']] = preprocessing.scale(exam_data[['writing score']])

In [20]:
exam_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group D,associate's degree,free/reduced,none,-0.484946,-0.621798,-0.252379
1,female,group B,high school,free/reduced,completed,-1.296570,-0.621798,0.050961
2,male,group C,associate's degree,free/reduced,completed,0.056137,-0.028982,-0.252379
3,female,group A,master's degree,free/reduced,none,-0.552581,0.497965,0.232965
4,male,group B,some high school,standard,completed,1.544115,1.222518,1.142985
5,female,group C,bachelor's degree,standard,completed,-0.890758,0.036886,-0.009707
6,male,group C,some high school,free/reduced,none,-1.026028,-0.753535,-0.980395
7,female,group C,bachelor's degree,standard,completed,1.138303,1.617729,1.628329
8,male,group B,some college,standard,none,-0.823122,-1.478088,-1.101731
9,male,group B,some college,standard,none,-0.687852,-0.885272,-1.041063
10,male,group C,bachelor's degree,standard,none,0.259043,-0.226587,-0.434383
11,female,group B,some college,standard,none,-0.146769,0.432097,0.718309
12,female,group C,some college,standard,none,-1.634747,-1.478088,-1.223067
13,female,group C,some college,standard,none,-0.552581,-0.226587,-0.131043
14,male,group C,high school,standard,completed,1.408845,0.695571,0.900313
15,male,group D,some high school,standard,none,-0.011498,-0.885272,-1.101731
16,female,group E,master's degree,standard,none,2.085198,1.485992,1.385657
17,female,group D,some college,standard,completed,0.935397,1.683597,1.871001
18,male,group D,high school,free/reduced,completed,-0.349675,0.234492,0.232965
19,female,group C,bachelor's degree,standard,none,-1.093664,-0.885272,-0.737723
20,male,group B,associate's degree,standard,completed,0.123773,-0.358324,-0.191711
21,female,group B,some high school,standard,completed,0.056137,0.366229,0.475637
22,female,group A,high school,free/reduced,completed,-0.958393,0.300360,0.111629
23,male,group C,high school,free/reduced,none,0.935397,-0.292456,-0.313047
24,male,group C,high school,standard,none,0.191408,-1.346351,-1.101731
25,female,group B,some high school,standard,completed,1.408845,1.288387,1.567661
26,male,group C,some high school,free/reduced,completed,0.191408,0.168623,-0.555719
27,female,group C,some college,standard,none,1.341209,1.288387,1.203653
28,male,group E,some college,standard,completed,1.747021,0.563834,0.475637
29,female,group D,bachelor's degree,free/reduced,none,0.056137,0.893176,0.778977
...,...,...,...,...,...,...,...,...
70,female,group E,high school,free/reduced,none,-1.093664,-0.490061,-0.313047
71,male,group D,some college,standard,completed,-0.079133,-0.292456,-0.373715
72,female,group A,some college,standard,completed,-0.146769,-0.226587,0.172297
73,female,group D,associate's degree,standard,none,0.529585,1.354255,1.264321
74,male,group B,high school,standard,none,0.461950,0.234492,0.354301
75,female,group D,master's degree,free/reduced,completed,0.597220,0.497965,0.839645
76,female,group C,some college,standard,none,0.597220,1.420123,1.324989
77,male,group C,high school,standard,none,-0.079133,-0.555930,-0.555719
78,male,group B,high school,standard,none,-0.890758,-0.951140,-0.859059
79,male,group C,some high school,free/reduced,none,-1.296570,-1.412219,-1.587075
80,female,group C,bachelor's degree,standard,completed,1.003032,1.617729,1.749665
81,female,group B,associate's degree,standard,none,1.070668,1.749466,1.749665
82,male,group C,associate's degree,free/reduced,completed,-0.282039,-0.160719,-0.798391
83,female,group C,bachelor's degree,free/reduced,none,-0.620216,0.629702,0.354301
84,male,group C,high school,free/reduced,none,-2.581642,-2.663720,-2.800435
85,male,group C,associate's degree,free/reduced,completed,-0.349675,-0.226587,-0.677055
86,male,group B,some high school,free/reduced,none,0.191408,-0.621798,-0.434383
87,male,group B,some college,standard,none,-0.620216,-0.358324,-0.555719
88,male,group C,associate's degree,standard,completed,1.882292,1.551860,1.264321
89,male,group A,master's degree,standard,completed,1.273574,1.156650,0.960981
90,male,group B,some college,free/reduced,none,-0.214404,-0.226587,-0.434383
91,female,group C,some high school,standard,none,-1.228935,-0.424193,-0.919727
92,female,group B,bachelor's degree,standard,none,-0.484946,-0.621798,-0.434383
93,female,group C,bachelor's degree,standard,completed,1.070668,1.749466,1.203653
94,female,group C,some high school,standard,completed,0.259043,0.563834,0.475637
95,female,group B,associate's degree,free/reduced,completed,0.529585,0.893176,0.778977
96,male,group A,bachelor's degree,standard,none,0.123773,-0.358324,-0.434383
97,female,group C,bachelor's degree,free/reduced,none,-1.161299,-1.082877,-0.980395
98,female,group D,associate's degree,standard,none,1.070668,1.222518,1.203653
99,male,group A,bachelor's degree,standard,none,1.476480,0.497965,0.414969

<p>
after scalling mean will be zero(or almost zero)
and standerd deviation of the score is 1
<p>

In [22]:
math_avg = exam_data['math score'].mean()
reading_avg = exam_data['reading score'].mean()
writing_avg = exam_data['writing score'].mean()
print('Math Average',math_avg)
print('Reading Average',reading_avg)
print('Writing Average',writing_avg)

Math Average -3.3306690738754695e-17
Reading Average -1.27675647831893e-17
Writing Average -1.8873791418627663e-17

#### Labelencoder will use when there are meaningfull comparison between catorical variables

In [24]:
le = preprocessing.LabelEncoder()
exam_data['gender'] = le.fit_transform(exam_data['gender'].astype(str))
exam_data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,group D,associate's degree,free/reduced,none,-0.484946,-0.621798,-0.252379
1,0,group B,high school,free/reduced,completed,-1.296570,-0.621798,0.050961
2,1,group C,associate's degree,free/reduced,completed,0.056137,-0.028982,-0.252379
3,0,group A,master's degree,free/reduced,none,-0.552581,0.497965,0.232965
4,1,group B,some high school,standard,completed,1.544115,1.222518,1.142985

In [26]:
le.classes_  # this will give what perticular colum hold

array(['female', 'male'], dtype=object)

In [27]:
pd.get_dummies(exam_data['race/ethnicity']) # one hot representation for race/ethnicity field

    group A  group B  group C  group D  group E
0         0        0        0        1        0
1         0        1        0        0        0
2         0        0        1        0        0
3         1        0        0        0        0
4         0        1        0        0        0
5         0        0        1        0        0
6         0        0        1        0        0
7         0        0        1        0        0
8         0        1        0        0        0
9         0        1        0        0        0
10        0        0        1        0        0
11        0        1        0        0        0
12        0        0        1        0        0
13        0        0        1        0        0
14        0        0        1        0        0
15        0        0        0        1        0
16        0        0        0        0        1
17        0        0        0        1        0
18        0        0        0        1        0
19        0        0        1        0        0
20        0        1        0        0        0
21        0        1        0        0        0
22        1        0        0        0        0
23        0        0        1        0        0
24        0        0        1        0        0
25        0        1        0        0        0
26        0        0        1        0        0
27        0        0        1        0        0
28        0        0        0        0        1
29        0        0        0        1        0
..      ...      ...      ...      ...      ...
70        0        0        0        0        1
71        0        0        0        1        0
72        1        0        0        0        0
73        0        0        0        1        0
74        0        1        0        0        0
75        0        0        0        1        0
76        0        0        1        0        0
77        0        0        1        0        0
78        0        1        0        0        0
79        0        0        1        0        0
80        0        0        1        0        0
81        0        1        0        0        0
82        0        0        1        0        0
83        0        0        1        0        0
84        0        0        1        0        0
85        0        0        1        0        0
86        0        1        0        0        0
87        0        1        0        0        0
88        0        0        1        0        0
89        1        0        0        0        0
90        0        1        0        0        0
91        0        0        1        0        0
92        0        1        0        0        0
93        0        0        1        0        0
94        0        0        1        0        0
95        0        1        0        0        0
96        1        0        0        0        0
97        0        0        1        0        0
98        0        0        0        1        0
99        1        0        0        0        0

[100 rows x 5 columns]

In [69]:
exam_data = pd.get_dummies(exam_data, columns=['parental level of education', 
                                               'lunch', 
                                               'test preparation course'])

ValueError: labels ['parental level of education' 'lunch' 'test preparation course'] not contained in axis

In [70]:
exam_data

,gender,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_free/reduced,lunch_standard,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,test preparation course_completed,test preparation course_none
0,0,-0.484946,-0.621798,-0.252379,0,0,0,1,0,1,0,1,0,0,0,0,0,0,1
1,0,-1.296570,-0.621798,0.050961,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
2,1,0.056137,-0.028982,-0.252379,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0
3,0,-0.552581,0.497965,0.232965,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1
4,1,1.544115,1.222518,1.142985,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0
5,0,-0.890758,0.036886,-0.009707,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0
6,1,-1.026028,-0.753535,-0.980395,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1
7,0,1.138303,1.617729,1.628329,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0
8,1,-0.823122,-1.478088,-1.101731,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1
9,1,-0.687852,-0.885272,-1.041063,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1
10,1,0.259043,-0.226587,-0.434383,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1
11,0,-0.146769,0.432097,0.718309,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1
12,0,-1.634747,-1.478088,-1.223067,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1
13,0,-0.552581,-0.226587,-0.131043,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1
14,1,1.408845,0.695571,0.900313,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0
15,1,-0.011498,-0.885272,-1.101731,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1
16,0,2.085198,1.485992,1.385657,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1
17,0,0.935397,1.683597,1.871001,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0
18,1,-0.349675,0.234492,0.232965,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0
19,0,-1.093664,-0.885272,-0.737723,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1
20,1,0.123773,-0.358324,-0.191711,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0
21,0,0.056137,0.366229,0.475637,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0
22,0,-0.958393,0.300360,0.111629,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0
23,1,0.935397,-0.292456,-0.313047,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
24,1,0.191408,-1.346351,-1.101731,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1
25,0,1.408845,1.288387,1.567661,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0
26,1,0.191408,0.168623,-0.555719,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0
27,0,1.341209,1.288387,1.203653,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1
28,1,1.747021,0.563834,0.475637,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0
29,0,0.056137,0.893176,0.778977,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0,-1.093664,-0.490061,-0.313047,0,0,0,0,1,1,0,0,0,1,0,0,0,0,1
71,1,-0.079133,-0.292456,-0.373715,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0
72,0,-0.146769,-0.226587,0.172297,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0
73,0,0.529585,1.354255,1.264321,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1
74,1,0.461950,0.234492,0.354301,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1
75,0,0.597220,0.497965,0.839645,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0
76,0,0.597220,1.420123,1.324989,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1
77,1,-0.079133,-0.555930,-0.555719,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1
78,1,-0.890758,-0.951140,-0.859059,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1
79,1,-1.296570,-1.412219,-1.587075,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1
80,0,1.003032,1.617729,1.749665,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0
81,0,1.070668,1.749466,1.749665,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1
82,1,-0.282039,-0.160719,-0.798391,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0
83,0,-0.620216,0.629702,0.354301,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1
84,1,-2.581642,-2.663720,-2.800435,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
85,1,-0.349675,-0.226587,-0.677055,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0
86,1,0.191408,-0.621798,-0.434383,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1
87,1,-0.620216,-0.358324,-0.555719,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1
88,1,1.882292,1.551860,1.264321,0,0,1,0,0,0,1,1,0,0,0,0,0,1,0
89,1,1.273574,1.156650,0.960981,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0
90,1,-0.214404,-0.226587,-0.434383,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1
91,0,-1.228935,-0.424193,-0.919727,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1
92,0,-0.484946,-0.621798,-0.434383,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1
93,0,1.070668,1.749466,1.203653,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0
94,0,0.259043,0.563834,0.475637,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0
95,0,0.529585,0.893176,0.778977,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0
96,1,0.123773,-0.358324,-0.434383,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1
97,0,-1.161299,-1.082877,-0.980395,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1
98,0,1.070668,1.222518,1.203653,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1
99,1,1.476480,0.497965,0.414969,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1